[tool.poetry]
name = "filetags"
version = "0.2.0"
description = "Arbitrarily nestable tags for files"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
lark = "^1.1.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
coverage = "^7.5.3"
mypy = "^1.10.0"

[tool.poetry.scripts]
ftag = "filetags.src.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
